UACE_SUBJECTS = [
    "Agriculture",
    "Arabic",
    "Art and Design",
    "Biology",
    "Building Construction",
    "Chemistry",
    "Christian Religious Education",
    "Commerce",
    "Computer Studies",
    "Divinity",
    "Economics",
    "Entrepreneurship Education",
    "Fine Art",
    "Food and Nutrition",
    "French",
    "General Paper",
    "Geography",
    "German",
    "History",
    "ICT",
    "Islamic Religious Education",
    "Kiswahili",
    "Literature in English",
    "Luganda",
    "Mathematics",
    "Music",
    "Nutrition and Food Science",
    "Performing Arts",
    "Physics",
    "Runyankole",
    "Lusoga",
    "Luo",
    "Clothing and Textiles",
    "Sub-Mathematics",
    "Technical Drawing",
]
