from django.urls import path

from .views import (
    AdminCandidateDetailAPIView,
    AdminCandidatesAPIView,
    AdminCutoffExcelUploadAPIView,
    AdminCourseCutoffAPIView,
    AdminCutoffHistoryTemplateDownloadAPIView,
    AdminCutoffTemplateDownloadAPIView,
    AdminCoursesAPIView,
    AdminDashboardAPIView,
    AdminLoginAPIView,
    AdminLogoutAPIView,
    AnalyticsAPIView,
    CalculateWeightAPIView,
    CandidateLoginAPIView,
    CandidateSignupAPIView,
    CourseSubjectRequirementListAPIView,
    CourseSubjectRequirementUpdateAPIView,
    ExportPDFAPIView,
    PlannerCourseListAPIView,
    StrengthProfileAPIView,
    UACESubjectListAPIView,
)

urlpatterns = [
    path("admin/login", AdminLoginAPIView.as_view(), name="admin-login"),
    path("admin/logout", AdminLogoutAPIView.as_view(), name="admin-logout"),
    path("admin/dashboard", AdminDashboardAPIView.as_view(), name="admin-dashboard"),
    path("admin/users", AdminCandidatesAPIView.as_view(), name="admin-candidates"),
    path("admin/users/<int:candidate_id>", AdminCandidateDetailAPIView.as_view(), name="admin-candidate-detail"),
    path("admin/courses", AdminCoursesAPIView.as_view(), name="admin-courses"),
    path("admin/courses/<int:course_id>/cutoff", AdminCourseCutoffAPIView.as_view(), name="admin-course-cutoff"),
    path("admin/courses/<int:course_id>/requirements", CourseSubjectRequirementListAPIView.as_view(), name="admin-course-requirements"),
    path("admin/course-requirements", CourseSubjectRequirementUpdateAPIView.as_view(), name="admin-course-requirements-update"),
    path("admin/cutoffs/upload", AdminCutoffExcelUploadAPIView.as_view(), name="admin-cutoff-upload"),
    path("admin/analytics", AnalyticsAPIView.as_view(), name="admin-analytics"),
    path(
        "admin/templates/cutoff-csv",
        AdminCutoffTemplateDownloadAPIView.as_view(),
        name="admin-cutoff-template-download",
    ),
    path(
        "admin/templates/cutoff-history-csv",
        AdminCutoffHistoryTemplateDownloadAPIView.as_view(),
        name="admin-cutoff-history-template-download",
    ),
    path("auth/signup", CandidateSignupAPIView.as_view(), name="candidate-signup"),
    path("auth/login", CandidateLoginAPIView.as_view(), name="candidate-login"),
    path("calculate-weight", CalculateWeightAPIView.as_view(), name="calculate-weight"),
    path("uace-subjects", UACESubjectListAPIView.as_view(), name="uace-subjects"),
    path("planner-courses", PlannerCourseListAPIView.as_view(), name="planner-courses"),
    path("strength-profile", StrengthProfileAPIView.as_view(), name="strength-profile"),
    path("export-pdf", ExportPDFAPIView.as_view(), name="export-pdf"),
]
