# Generated by Django 5.1.6 on 2026-03-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_candidate_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCutoffHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("cutoff_weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutoff_history",
                        to="admissions.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("course", "year")},
            },
        ),
    ]
